apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  volumeName: jenkins-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
